name: CI/CD Workflow

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuración de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t meybili/githooks:latest .

      # Ejecutar el contenedor para probar localmente
      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name githooks-container meybili/githooks:latest
          sleep 5 # Esperar unos segundos para asegurar que el contenedor esté activo

      # Verificar que el servidor esté funcionando correctamente
      - name: Test application
        run: |
          curl --fail http://localhost:3000 || (echo "Server test failed" && exit 1)

      # Subir la imagen a Docker Hub si las pruebas son exitosas
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push meybili/githooks:latest